# Generated by ChatGPT for MoneyPro business backup history.
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_business_email_settings_outgoingemaillog"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("running", "Running"), ("success", "Success"), ("failed", "Failed"), ("deleted", "Deleted")], default="running", max_length=12)),
                ("backup_type", models.CharField(choices=[("xlsx", "Excel workbook"), ("json", "JSON package")], default="xlsx", max_length=10)),
                ("storage_key", models.CharField(blank=True, max_length=500)),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                ("table_count", models.PositiveIntegerField(default=0)),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("retention_days", models.PositiveIntegerField(default=7)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="backup_logs", to="core.business")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_backup_logs", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Backup log",
                "verbose_name_plural": "Backup logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
