# Generated by Django 5.2.11 on 2026-05-07 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_business_email_settings_outgoingemaillog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.business')),
            ],
            options={
                'ordering': ['business', 'code'],
                'unique_together': {('business', 'code')},
            },
        ),
    ]
