# Generated by Django 5.2.11 on 2026-05-07 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_backuplog'),
        ('core', '0003_businessfeature'),
    ]

    operations = [
    ]
