# Generated by Django 5.2.11 on 2026-03-12 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('invoices', '0001_initial'),
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='ledger.contact'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='income_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_income_for', to='ledger.transaction'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='ledger.job'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='revises',
            field=models.ForeignKey(blank=True, help_text='If set, this invoice is a revision of another invoice.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='invoices.invoice'),
        ),
        migrations.AddField(
            model_name='invoicecounter',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.business'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.business'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='ledger.subcategory'),
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.business'),
        ),
        migrations.AddField(
            model_name='invoicepayment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoices.invoice'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('business', 'invoice_number'), name='uniq_invoice_number_per_business'),
        ),
        migrations.AddConstraint(
            model_name='invoicecounter',
            constraint=models.UniqueConstraint(fields=('business', 'year'), name='uniq_invoice_counter_business_year'),
        ),
    ]
