# Generated by Django 5.2.11 on 2026-02-06 22:39

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(blank=True, max_length=120)),
                ('category_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('book_reports', models.BooleanField(default=True)),
                ('tax_reports', models.BooleanField(default=True)),
                ('schedule_c_line', models.CharField(blank=True, choices=[('gross_receipts', '1'), ('returns_allowances', '2'), ('advertising', '8'), ('car_truck', '9'), ('commissions_fees', '10'), ('contract_labor', '11'), ('depletion', '12'), ('depreciation', '13'), ('employee_benefits', '14'), ('insurance', '15'), ('interest_mortgage', '16a'), ('interest_other', '16b'), ('legal_pro', '17'), ('office', '18'), ('pension_profit_sharing', '19'), ('rent_lease_vehicles', '20a'), ('rent_lease_other', '20b'), ('repairs', '21'), ('supplies', '22'), ('taxes_licenses', '23'), ('travel', '24a'), ('meals', '24b'), ('utilities', '25'), ('wages', '26'), ('energy_efficient_buildings', '27a'), ('other_expenses_part_v', '27b')], default='', max_length=30)),
                ('report_group', models.CharField(blank=True, max_length=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category_type', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField(default=2026)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Payee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address1', models.CharField(blank=True, max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, default='US', max_length=50)),
                ('is_vendor', models.BooleanField(default=True)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_contractor', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='PayeeTaxProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_1099_eligible', models.BooleanField(default=False)),
                ('entity_type', models.CharField(blank=True, choices=[('individual', 'Individual / Sole Proprietor'), ('llc', 'LLC'), ('partnership', 'Partnership'), ('c_corp', 'C Corporation'), ('s_corp', 'S Corporation'), ('other', 'Other')], max_length=25)),
                ('tin_type', models.CharField(blank=True, choices=[('ssn', 'SSN'), ('ein', 'EIN')], max_length=10)),
                ('tin_last4', models.CharField(blank=True, max_length=4)),
                ('w9_status', models.CharField(choices=[('missing', 'Missing'), ('requested', 'Requested'), ('received', 'Received'), ('verified', 'Verified')], default='missing', max_length=15)),
                ('w9_document', models.FileField(blank=True, null=True, upload_to='w9/')),
                ('notes', models.TextField(blank=True)),
                ('payee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_profile', to='ledger.payee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(blank=True, max_length=140, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('book_enabled', models.BooleanField(default=True)),
                ('tax_enabled', models.BooleanField(default=True)),
                ('schedule_c_line', models.CharField(blank=True, choices=[('gross_receipts', '1'), ('returns_allowances', '2'), ('advertising', '8'), ('car_truck', '9'), ('commissions_fees', '10'), ('contract_labor', '11'), ('depletion', '12'), ('depreciation', '13'), ('employee_benefits', '14'), ('insurance', '15'), ('interest_mortgage', '16a'), ('interest_other', '16b'), ('legal_pro', '17'), ('office', '18'), ('pension_profit_sharing', '19'), ('rent_lease_vehicles', '20a'), ('rent_lease_other', '20b'), ('repairs', '21'), ('supplies', '22'), ('taxes_licenses', '23'), ('travel', '24a'), ('meals', '24b'), ('utilities', '25'), ('wages', '26'), ('energy_efficient_buildings', '27a'), ('other_expenses_part_v', '27b')], default='', help_text='Optional override. If blank, reports may use Category.schedule_c_line.', max_length=30)),
                ('deduction_rule', models.CharField(choices=[('full', '100% deductible'), ('meals_50', 'Meals (50%)'), ('nondeductible', 'Not deductible')], default='full', max_length=20)),
                ('is_1099_reportable_default', models.BooleanField(default=False)),
                ('is_capitalizable', models.BooleanField(default=False)),
                ('requires_payee', models.BooleanField(default=False)),
                ('payee_role', models.CharField(choices=[('any', 'Any'), ('vendor', 'Vendor'), ('contractor', 'Contractor'), ('customer', 'Customer')], default='any', max_length=15)),
                ('requires_transport', models.BooleanField(default=False)),
                ('requires_vehicle', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='ledger.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category__category_type', 'category__sort_order', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('description', models.CharField(max_length=255)),
                ('invoice_number', models.CharField(blank=True, max_length=25)),
                ('transport_type', models.CharField(blank=True, choices=[('', '—'), ('personal_vehicle', 'Personal vehicle'), ('rental_car', 'Rental car'), ('business_vehicle', 'Business vehicle')], default='', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='ledger.category')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='ledger.job')),
                ('payee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='ledger.payee')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='ledger.subcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('user', 'name', 'category_type'), name='uniq_category_user_name_type'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('user', 'category_type', 'slug'), name='uniq_category_user_type_slug'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(fields=('user', 'year', 'title'), name='uniq_job_user_year_title'),
        ),
        migrations.AddConstraint(
            model_name='payee',
            constraint=models.UniqueConstraint(fields=('user', 'display_name'), name='uniq_payee_display_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='payeetaxprofile',
            constraint=models.UniqueConstraint(fields=('user', 'payee'), name='uniq_taxprofile_payee_per_user'),
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(fields=('user', 'category', 'name'), name='uniq_subcategory_user_cat_name'),
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('slug__isnull', False), models.Q(('slug', ''), _negated=True)), fields=('user', 'slug'), name='uniq_subcategory_user_slug_nonblank'),
        ),
    ]
