# Generated by ChatGPT for MoneyPro Jobs upgrade

from __future__ import annotations

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


def _populate_job_numbers(apps, schema_editor):
    Job = apps.get_model("ledger", "Job")
    now = timezone.now()

    # Fill missing job_number values for any pre-existing rows.
    # Deterministic and unique within the table.
    for job in Job.objects.all().only("id", "job_number", "created_at", "updated_at"):
        updates = []

        val = (getattr(job, "job_number", "") or "").strip()
        if not val:
            job.job_number = f"JOB-{job.id}"
            updates.append("job_number")

        if getattr(job, "created_at", None) is None:
            job.created_at = now
            updates.append("created_at")

        if getattr(job, "updated_at", None) is None:
            job.updated_at = now
            updates.append("updated_at")

        if updates:
            job.save(update_fields=updates)


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0001_initial"),
    ]

    operations = [
        # Replace the old uniqueness rule (business+year+title)
        migrations.RemoveConstraint(
            model_name="job",
            name="uniq_job_business_year_title",
        ),

        # New fields (added nullable/blank first for safe migration)
        migrations.AddField(
            model_name="job",
            name="job_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="client",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional. Select a Payee marked as a Customer.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="client_jobs",
                to="ledger.payee",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("commercial", "Commercial"),
                    ("real_estate", "Real Estate"),
                    ("inspection", "Inspection"),
                    ("construction", "Construction"),
                    ("photography", "Photography"),
                    ("mapping", "Mapping"),
                    ("training", "Training"),
                    ("internal", "Internal"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="city",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="job",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="job",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="job",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),

        migrations.RunPython(_populate_job_numbers, migrations.RunPython.noop),

        # Now make job_number required at the DB-level
        migrations.AlterField(
            model_name="job",
            name="job_number",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="job",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),

        # Drop the old year field
        migrations.RemoveField(
            model_name="job",
            name="year",
        ),

        # New uniqueness rule
        migrations.AddConstraint(
            model_name="job",
            constraint=models.UniqueConstraint(
                fields=("business", "job_number"),
                name="uniq_job_business_job_number",
            ),
        ),

        migrations.AlterModelOptions(
            name="job",
            options={"ordering": ["-is_active", "job_number", "title"]},
        ),
    ]
