# Generated by Django 5.2.11 on 2026-03-12 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='vehicles.vehicle'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('business', 'name', 'category_type'), name='uniq_category_business_name_type'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('business', 'category_type', 'slug'), name='uniq_category_business_type_slug'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('business', 'display_name'), name='uniq_contact_display_name_per_business'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('client_code__isnull', False), models.Q(('client_code', ''), _negated=True)), fields=('business', 'client_code'), name='uniq_contact_client_code_per_business_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(fields=('business', 'job_number'), name='uniq_job_business_job_number'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(fields=('business', 'job_year', 'job_seq'), name='uniq_job_business_year_seq'),
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(fields=('business', 'category', 'name'), name='uniq_subcategory_business_cat_name'),
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('slug__isnull', False), models.Q(('slug', ''), _negated=True)), fields=('business', 'slug'), name='uniq_subcategory_business_slug_nonblank'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('business', 'name'), name='uniq_team_per_business_name'),
        ),
    ]
