# Generated by Django 5.2.11 on 2026-02-25 04:52

import django.db.models.deletion
import ledger.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_rename_assets_asse_business_a9c6e1_idx_assets_asse_busines_622638_idx_and_more'),
        ('ledger', '0003_client_code_and_job_numbering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-is_active', '-job_year', 'job_number', 'label']},
        ),
        migrations.AddField(
            model_name='subcategory',
            name='account_type',
            field=models.CharField(choices=[('expense', 'Expense'), ('income', 'Income'), ('asset', 'Asset'), ('liability', 'Liability'), ('journal', 'Journal Only')], default='expense', max_length=20),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='requires_asset',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='requires_invoice_number',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='requires_job',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='requires_receipt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='requires_team',
            field=models.BooleanField(default=False),
        ),

        migrations.AlterField(
            model_name='job',
            name='job_year',
            field=models.PositiveIntegerField(default=ledger.models.current_year),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trans_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('asset', 'Asset'), ('liability', 'Liability'), ('journal', 'Journal Only')], editable=False, max_length=10),
        ),
    ]
