# Generated by Django 5.2.11 on 2026-03-12 23:17

import contractor.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorW9Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('entity_type', models.CharField(blank=True, max_length=25)),
                ('tin_type', models.CharField(blank=True, max_length=10)),
                ('tin_last4', models.CharField(blank=True, max_length=4)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('signature_name', models.CharField(blank=True, max_length=255)),
                ('signature_data', models.TextField(blank=True)),
                ('submitted_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('submitted_ua', models.CharField(blank=True, max_length=255)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Contractor1099',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_year', models.PositiveIntegerField(db_index=True)),
                ('copy_b_pdf', models.FileField(blank=True, null=True, upload_to=contractor.models.contractor_1099_upload_path)),
                ('copy_1_pdf', models.FileField(blank=True, null=True, upload_to=contractor.models.contractor_1099_upload_path)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('emailed_to', models.EmailField(blank=True, max_length=254)),
                ('email_count', models.PositiveIntegerField(default=0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.business')),
            ],
            options={
                'ordering': ['-tax_year', '-generated_at', '-id'],
            },
        ),
    ]
