# Generated by ChatGPT on 2026-02-25
from __future__ import annotations

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),  # Business and mixin base
        ("ledger", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractorW9Submission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=255)),
                ("business_name", models.CharField(blank=True, max_length=255)),
                ("entity_type", models.CharField(blank=True, max_length=25)),
                ("tin_type", models.CharField(blank=True, max_length=10)),
                ("tin_last4", models.CharField(blank=True, max_length=4)),
                ("address_line1", models.CharField(blank=True, max_length=255)),
                ("address_line2", models.CharField(blank=True, max_length=255)),
                ("signature_name", models.CharField(blank=True, max_length=255)),
                ("signature_data", models.TextField(blank=True)),
                ("submitted_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("submitted_ua", models.CharField(blank=True, max_length=255)),
                ("submitted_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="contractor_contractorw9submission_set", to="core.business")),
                ("contact", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="w9_submissions", to="ledger.contact")),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.AddIndex(
            model_name="contractorw9submission",
            index=models.Index(fields=["business", "contact"], name="ctr_w9_bus_contact_idx"),
        ),
    ]
