# Generated by Django 5.2.11 on 2026-03-12 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contractor', '0001_initial'),
        ('core', '0001_initial'),
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor1099',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms_1099', to='ledger.contact'),
        ),
        migrations.AddField(
            model_name='contractorw9submission',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.business'),
        ),
        migrations.AddField(
            model_name='contractorw9submission',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='w9_submissions', to='ledger.contact'),
        ),
        migrations.AddIndex(
            model_name='contractor1099',
            index=models.Index(fields=['business', 'tax_year'], name='ctr_1099_bus_year_idx'),
        ),
        migrations.AddIndex(
            model_name='contractor1099',
            index=models.Index(fields=['business', 'contact', 'tax_year'], name='ctr_1099_bus_contact_year_idx'),
        ),
        migrations.AddConstraint(
            model_name='contractor1099',
            constraint=models.UniqueConstraint(fields=('business', 'contact', 'tax_year'), name='uniq_1099_per_contact_year'),
        ),
        migrations.AddIndex(
            model_name='contractorw9submission',
            index=models.Index(fields=['business', 'contact'], name='ctr_w9_bus_contact_idx'),
        ),
    ]
