# Generated by Django 5.2.11 on 2026-03-12 23:17

import assets.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('equipment', 'Equipment'), ('vehicle', 'Vehicle'), ('computer', 'Computer'), ('furniture', 'Furniture'), ('other', 'Other')], default='equipment', max_length=20)),
                ('purchase_date', models.DateField()),
                ('placed_in_service_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('useful_life_years', models.PositiveSmallIntegerField(default=5)),
                ('depreciation_method', models.CharField(choices=[('macrs_5', 'MACRS 5-Year'), ('macrs_7', 'MACRS 7-Year'), ('straight_line', 'Straight Line'), ('section_179', 'Section 179')], default='macrs_5', max_length=50)),
                ('section_179_amount', models.DecimalField(blank=True, decimal_places=2, help_text='If using Section 179, enter the amount elected for immediate deduction.', max_digits=12, null=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to=assets.models.asset_receipt_upload_to)),
                ('disposed_date', models.DateField(blank=True, null=True)),
                ('disposal_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.business')),
            ],
            options={
                'ordering': ['-purchase_date', 'name'],
            },
        ),
    ]
