# Generated by Django 5.2.11 on 2026-02-25 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='asset',
            new_name='assets_asse_busines_622638_idx',
            old_name='assets_asse_business_a9c6e1_idx',
        ),
        migrations.RenameIndex(
            model_name='asset',
            new_name='assets_asse_busines_067ce9_idx',
            old_name='assets_asse_business_3a4c9c_idx',
        ),
    ]
