# Generated by Django 5.2.11 on 2026-03-12 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='vehicle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_record', to='vehicles.vehicle'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['business', 'asset_type'], name='assets_asse_busines_622638_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['business', 'purchase_date'], name='assets_asse_busines_067ce9_idx'),
        ),
    ]
