# Generated by Django 5.2.11 on 2026-02-06 22:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='What you want to see in dropdowns (e.g., 2018 Ford F-150).', max_length=120)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('make', models.CharField(blank=True, max_length=60)),
                ('model', models.CharField(blank=True, max_length=60)),
                ('vin_last6', models.CharField(blank=True, max_length=6)),
                ('plate', models.CharField(blank=True, max_length=20)),
                ('in_service_date', models.DateField(blank=True, default=None, null=True)),
                ('in_service_mileage', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('sold_date', models.DateField(blank=True, default=None, null=True)),
                ('is_business', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='VehicleMiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('begin', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('end', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('total', models.DecimalField(blank=True, decimal_places=1, editable=False, max_digits=10, null=True)),
                ('mileage_type', models.CharField(choices=[('business', 'Business'), ('commuting', 'Commuting'), ('other', 'Other'), ('reimbursed', 'Reimbursed')], default='business', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='miles_entries', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VehicleYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2026)),
                ('odometer_start', models.DecimalField(decimal_places=1, help_text='Odometer reading on Jan 1 (or start of year).', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('odometer_end', models.DecimalField(blank=True, decimal_places=1, help_text='Odometer reading on Dec 31 (or end of year).', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('deduction_method', models.CharField(choices=[('standard_mileage', 'Standard mileage'), ('actual_expenses', 'Actual expenses')], default='standard_mileage', max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='years', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-year', 'vehicle__label'],
            },
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('user', 'label'), name='uniq_vehicle_user_label'),
        ),
        migrations.AddIndex(
            model_name='vehiclemiles',
            index=models.Index(fields=['user', 'date'], name='vehicles_ve_user_id_5c6007_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclemiles',
            index=models.Index(fields=['user', 'vehicle'], name='vehicles_ve_user_id_9d76f7_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclemiles',
            index=models.Index(fields=['user', 'mileage_type'], name='vehicles_ve_user_id_2751f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehicleyear',
            constraint=models.UniqueConstraint(fields=('user', 'vehicle', 'year'), name='uniq_vehicle_year_per_user'),
        ),
    ]
