# Generated by ChatGPT for MoneyPro vehicles loan amortization support.

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0003_vehicleyear_annual_interest_paid"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleLoan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("purchase_date", models.DateField(help_text="Date the vehicle was purchased.")),
                ("first_payment_date", models.DateField(blank=True, help_text="Optional first loan payment date.", null=True)),
                ("original_loan_amount", models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ("annual_interest_rate", models.DecimalField(decimal_places=4, help_text="Annual interest rate as a percent, e.g. 7.2500", max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ("number_of_payments", models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.business")),
                ("vehicle", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="loan", to="vehicles.vehicle")),
            ],
            options={
                "ordering": ["vehicle__label"],
            },
        ),
        migrations.CreateModel(
            name="VehicleLoanPayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("payment_number", models.PositiveIntegerField()),
                ("payment_date", models.DateField()),
                ("beginning_balance", models.DecimalField(decimal_places=2, max_digits=12)),
                ("payment_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("principal_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("interest_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("ending_balance", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("business", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.business")),
                ("loan", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payments", to="vehicles.vehicleloan")),
            ],
            options={
                "ordering": ["payment_date", "payment_number"],
            },
        ),
        migrations.AddConstraint(
            model_name="vehicleloanpayment",
            constraint=models.UniqueConstraint(fields=("loan", "payment_number"), name="uniq_vehicle_loan_payment_number"),
        ),
        migrations.AddIndex(
            model_name="vehicleloanpayment",
            index=models.Index(fields=["business", "payment_date"], name="vehicles_ve_busines_loanpd_idx"),
        ),
    ]
