# Generated by Django 5.2.11 on 2026-04-21 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_vehicleloan_and_amortization'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vehicleloanpayment',
            new_name='vehicles_ve_busines_ad11d0_idx',
            old_name='vehicles_ve_busines_loanpd_idx',
        ),
    ]
